export interface ImageManifestEntry {
  id: string;
  category: 'product' | 'configurator' | 'room' | 'material' | 'studio' | 'hero' | 'social';
  productSlug?: string;
  roomSlug?: string;
  fileName: string;
  filePath: string;
  role: string;
  dimensions: { width: number; height: number };
  aspectRatio: string;
  focalPoint: string;
  alt: string;
  promptFoundation: string;
  reviewStatus: 'Approved' | 'Review' | 'Regenerated';
  isIllustrative: boolean;
}

export const IMAGE_MANIFEST: ImageManifestEntry[] = [
  {
    id: 'img-hero-home',
    category: 'hero',
    fileName: 'hero_contemporary_living.png',
    filePath: '/images/hero/hero_contemporary_living.png',
    role: 'Homepage Main Editorial Hero',
    dimensions: { width: 2400, height: 1350 },
    aspectRatio: '16:9',
    focalPoint: 'Center-Right',
    alt: 'Serene contemporary Indian living room featuring Niyata low-profile teak furniture, natural morning light, and lime-wash walls',
    promptFoundation:
      'Editorial architectural photography of a serene Indian urban living room with high ceilings, warm natural morning light, polished terrazzo flooring, a low-slung teak modular sofa in oat linen, circular fluted sandstone coffee table, understated potted monstera, warm lime-wash walls, calm warm mineral palette, no clutter, zero AI text.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Rooms
  {
    id: 'img-room-bandra',
    category: 'room',
    roomSlug: 'compact-urban-living-bandra',
    fileName: 'room_urban_living_bandra.png',
    filePath: '/images/rooms/room_urban_living_bandra.png',
    role: 'Compact 2BHK Living Room Scene',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Compact 2BHK urban living room in Bandra featuring Prana 2-seat sofa, Aalap coffee table, and Tarang side table',
    promptFoundation:
      'Contemporary compact 2BHK Indian apartment living room in Mumbai, soft natural daylight, off-white lime-wash walls, grey aggregate terrazzo floor, 2-seat low profile teak sofa in oat linen, circular fluted coffee table, tripod side table, thoughtful urban proportions, architectural commercial photography.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-room-koramangala',
    category: 'room',
    roomSlug: 'family-living-room-koramangala',
    fileName: 'room_family_living_koramangala.png',
    filePath: '/images/rooms/room_family_living_koramangala.png',
    role: 'Generous 3BHK Family Living Room Scene',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center-Left',
    alt: 'Family living room in Koramangala with Prana chaise sofa in moss fabric, Kaya lounge chairs, and Kosh credenza',
    promptFoundation:
      'Warm contemporary 3BHK apartment living room in Bengaluru opening to a verdant balcony terrace, concrete screed flooring with brass divider inlays, 3-seat teak sofa with extended chaise in muted moss green bouclé, low wooden lounge chair, low slatted credenza, soft afternoon daylight, serene and grounded.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-room-ahmedabad',
    category: 'room',
    roomSlug: 'contemporary-dining-ahmedabad',
    fileName: 'room_dining_ahmedabad.png',
    filePath: '/images/rooms/room_dining_ahmedabad.png',
    role: 'Dining Room Scene',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Dining room in Ahmedabad with Veda trestle dining table, six Dhyaan spindle chairs, and Kosh credenza against brick walls',
    promptFoundation:
      'Warm Indian dining room with exposed terracotta wire-cut brickwork, honed Kota stone flooring, a solid teak 6-seater trestle dining table, six teak spindle dining chairs with steam-bent backrests, natural skylight illuminating the table center, ceramic tableware.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-room-indiranagar',
    category: 'room',
    roomSlug: 'calm-bedroom-indiranagar',
    fileName: 'room_bedroom_indiranagar.png',
    filePath: '/images/rooms/room_bedroom_indiranagar.png',
    role: 'Primary Bedroom Suite Scene',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Primary bedroom suite featuring Nidra low platform bed, Setu bench, and Tarang side tables',
    promptFoundation:
      'Quiet minimal master bedroom in an Indian urban apartment, warm chalk plaster walls, solid teak low platform king bed with floating plinth, upholstered oatmeal linen headrest, tailored bouclé bench at bed foot, floor lamp with soft 2700K ambient light, tranquil sanctuary atmosphere.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-room-surat',
    category: 'room',
    roomSlug: 'reading-corner-study-surat',
    fileName: 'room_study_surat.png',
    filePath: '/images/rooms/room_study_surat.png',
    role: 'Urban Study & Reading Sanctuary Scene',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Urban study reading corner in Surat with Sopan open shelving, Kaya lounge chair, and Aksh floor lamp',
    promptFoundation:
      'Modern high-rise apartment study reading corner in Surat, large window overlooking city, grey marble tile floor, open teak and matte charcoal steel modular shelving unit filled with art books, low pitched teak lounge chair with linen cushion, warm brass floor lamp, contemplative atmosphere.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Configurator Sofa Renders (9 variations)
  {
    id: 'img-sofa-2s-oat',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_2seat_oat.png',
    filePath: '/images/products/prana_sofa_2seat_oat.png',
    role: '2-Seat Compact / Oat Natural Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 2-Seat Compact Modular Sofa in Oat Natural linen upholstery on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 2-seat compact low-profile modern sofa, solid teakwood base plinth, warm oatmeal textured linen upholstery, clean studio backdrop, natural soft lighting, physically accurate proportions.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-2s-moss',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_2seat_moss.png',
    filePath: '/images/products/prana_sofa_2seat_moss.png',
    role: '2-Seat Compact / Muted Moss Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 2-Seat Compact Modular Sofa in Muted Moss bouclé upholstery on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 2-seat compact low-profile modern sofa, identical solid teakwood base plinth, muted olive moss green woven bouclé upholstery, exact same camera angle and lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-2s-clay',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_2seat_clay.png',
    filePath: '/images/products/prana_sofa_2seat_clay.png',
    role: '2-Seat Compact / Terracotta Clay Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 2-Seat Compact Modular Sofa in Terracotta Clay flatweave on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 2-seat compact low-profile modern sofa, identical solid teakwood base plinth, warm terracotta clay textured weave, exact same camera angle and lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-3s-oat',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_3seat_oat.png',
    filePath: '/images/products/prana_sofa_3seat_oat.png',
    role: '3-Seat Standard / Oat Natural Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 3-Seat Standard Modular Sofa in Oat Natural linen upholstery on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 3-seat wide low-profile modern sofa, solid teakwood base plinth, warm oatmeal textured linen upholstery, clean studio backdrop, natural soft lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-3s-moss',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_3seat_moss.png',
    filePath: '/images/products/prana_sofa_3seat_moss.png',
    role: '3-Seat Standard / Muted Moss Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 3-Seat Standard Modular Sofa in Muted Moss bouclé upholstery on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 3-seat wide low-profile modern sofa, solid teakwood base plinth, muted olive moss green woven bouclé upholstery, exact same camera angle and lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-3s-clay',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_3seat_clay.png',
    filePath: '/images/products/prana_sofa_3seat_clay.png',
    role: '3-Seat Standard / Terracotta Clay Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana 3-Seat Standard Modular Sofa in Terracotta Clay flatweave on solid teak base',
    promptFoundation: 'Commercial studio product photography of a 3-seat wide low-profile modern sofa, solid teakwood base plinth, warm terracotta clay flatweave upholstery, exact same camera angle and lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-chaise-oat',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_chaise_oat.png',
    filePath: '/images/products/prana_sofa_chaise_oat.png',
    role: '3-Seat Chaise / Oat Natural Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana Chaise Modular Sofa in Oat Natural fabric on solid teak base',
    promptFoundation: 'Commercial studio product photography of an L-shaped sectional modular sofa with extended chaise lounge, solid teakwood base plinth, warm oatmeal textured linen upholstery, clean studio backdrop.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-chaise-moss',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_chaise_moss.png',
    filePath: '/images/products/prana_sofa_chaise_moss.png',
    role: '3-Seat Chaise / Muted Moss Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana Chaise Modular Sofa in Muted Moss bouclé on solid teak base',
    promptFoundation: 'Commercial studio product photography of an L-shaped sectional modular sofa with extended chaise lounge, solid teakwood base plinth, muted olive moss green woven bouclé upholstery, exact same camera angle.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-chaise-clay',
    category: 'configurator',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_chaise_clay.png',
    filePath: '/images/products/prana_sofa_chaise_clay.png',
    role: '3-Seat Chaise / Terracotta Clay Fabric',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana Chaise Modular Sofa in Terracotta Clay flatweave on solid teak base',
    promptFoundation: 'Commercial studio product photography of an L-shaped sectional modular sofa with extended chaise lounge, solid teakwood base plinth, warm terracotta clay flatweave, exact same camera angle.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sofa-detail-joinery',
    category: 'product',
    productSlug: 'prana-modular-sofa',
    fileName: 'prana_sofa_detail_joinery.png',
    filePath: '/images/products/prana_sofa_detail_joinery.png',
    role: 'Sofa Teak Plinth Joinery Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Prana Sofa solid teak plinth joinery and fabric detail',
    promptFoundation: 'Close-up macro photography of rounded solid teak corner plinth wood joinery meeting textured woven upholstery fabric on a modern low sofa, sharp focus on wood grain and tactile textile weave.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Kaya Lounge Chair
  {
    id: 'img-kaya-hero',
    category: 'product',
    productSlug: 'kaya-lounge-chair',
    fileName: 'kaya_lounge_chair_hero.png',
    filePath: '/images/products/kaya_lounge_chair_hero.png',
    role: 'Kaya Chair Hero Front 3/4',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Kaya Low Lounge Chair in solid teakwood with mineral sand linen upholstery',
    promptFoundation: 'Product photography of a low sculptural modern lounge chair, solid seasoned teakwood pitched frame, natural mineral sand linen-cotton sling cushion, clean warm architectural background, soft natural daylight.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-kaya-side',
    category: 'product',
    productSlug: 'kaya-lounge-chair',
    fileName: 'kaya_lounge_chair_side.png',
    filePath: '/images/products/kaya_lounge_chair_side.png',
    role: 'Kaya Chair Side Profile',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Side profile of Kaya Lounge Chair showing angled ergonomic teak frame',
    promptFoundation: 'Side profile view of the Kaya low lounge chair, showing the 105-degree reclined pitch of the teakwood timber frame, exposed bridle joinery, linen cushion profile, neutral warm background.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-kaya-detail',
    category: 'product',
    productSlug: 'kaya-lounge-chair',
    fileName: 'kaya_lounge_chair_detail.png',
    filePath: '/images/products/kaya_lounge_chair_detail.png',
    role: 'Kaya Chair Joinery Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up detail of bridle wood joinery and textured linen weave on Kaya Chair',
    promptFoundation: 'Macro detail photograph of exposed timber dowel bridle joinery on a teak armchair armrest and textured linen textile weave.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Setu Bench
  {
    id: 'img-setu-hero',
    category: 'product',
    productSlug: 'setu-bench',
    fileName: 'setu_bench_hero.png',
    filePath: '/images/products/setu_bench_hero.png',
    role: 'Setu Bench Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Setu Upholstered Bench with cream bouclé cushion and solid walnut legs with brass accents',
    promptFoundation: 'Commercial studio product shot of a 120cm minimalist upholstered bench, solid American walnut cylindrical legs with spun brass collars, warm cream bouclé cushioned top, neutral mineral studio background.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-setu-room',
    category: 'product',
    productSlug: 'setu-bench',
    fileName: 'setu_bench_room.png',
    filePath: '/images/products/setu_bench_room.png',
    role: 'Setu Bench in Bedroom',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Setu Bench positioned at the foot of the Nidra Platform Bed',
    promptFoundation: 'Interior ambient shot of the Setu walnut and cream bouclé bench placed gracefully at the foot of a low wooden platform bed in a serene bedroom.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-setu-detail',
    category: 'product',
    productSlug: 'setu-bench',
    fileName: 'setu_bench_detail.png',
    filePath: '/images/products/setu_bench_detail.png',
    role: 'Setu Bench Brass Leg Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro detail of Setu Bench brass ferrule and bouclé fabric',
    promptFoundation: 'Macro close-up of a solid brass ferrule accent collar on a turned walnut bench leg and the tactile cream bouclé fabric edge.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Aalap Coffee Table
  {
    id: 'img-aalap-hero',
    category: 'product',
    productSlug: 'aalap-coffee-table',
    fileName: 'aalap_coffee_table_hero.png',
    filePath: '/images/products/aalap_coffee_table_hero.png',
    role: 'Aalap Coffee Table Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Aalap Fluted Coffee Table with honed sandstone top and solid teak fluted pedestal',
    promptFoundation: 'Product photography of a round coffee table, cylindrical fluted solid teakwood pedestal base, honed beige Dholpur sandstone circular top with chamfered rim, soft architectural lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-aalap-top',
    category: 'product',
    productSlug: 'aalap-coffee-table',
    fileName: 'aalap_coffee_table_top.png',
    filePath: '/images/products/aalap_coffee_table_top.png',
    role: 'Aalap Coffee Table Top View',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Top-down three-quarter perspective of Aalap Coffee Table showing sandstone grain',
    promptFoundation: 'Elevated 45-degree angle view of the round Aalap coffee table highlighting the natural honed beige sandstone top texture and perimeter bevel.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-aalap-detail',
    category: 'product',
    productSlug: 'aalap-coffee-table',
    fileName: 'aalap_coffee_table_detail.png',
    filePath: '/images/products/aalap_coffee_table_detail.png',
    role: 'Aalap Fluted Pedestal Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up of hand-milled teak fluting and chamfered sandstone rim on Aalap Table',
    promptFoundation: 'Extreme macro detail of vertical rhythmic solid teak fluting meeting the chamfered sandstone tabletop edge.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Tarang Side Table
  {
    id: 'img-tarang-hero',
    category: 'product',
    productSlug: 'tarang-side-table',
    fileName: 'tarang_side_table_hero.png',
    filePath: '/images/products/tarang_side_table_hero.png',
    role: 'Tarang Side Table Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Tarang Side Table with turned teak dished top and black tripod steel legs',
    promptFoundation: 'Commercial studio product shot of a small tripod side table, lathe-turned round solid teak tabletop with an 8mm raised rim, slender matte charcoal powder-coated steel tripod legs.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-tarang-angle',
    category: 'product',
    productSlug: 'tarang-side-table',
    fileName: 'tarang_side_table_angle.png',
    filePath: '/images/products/tarang_side_table_angle.png',
    role: 'Tarang Side Table Angle',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Three-quarter ambient view of Tarang Side Table beside a lounge chair',
    promptFoundation: 'Ambient lifestyle shot of the Tarang side table holding a brass chai glass beside a teak lounge chair.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-tarang-detail',
    category: 'product',
    productSlug: 'tarang-side-table',
    fileName: 'tarang_side_table_detail.png',
    filePath: '/images/products/tarang_side_table_detail.png',
    role: 'Tarang Dished Rim Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Detail of dished teak rim and brass connection on Tarang Side Table',
    promptFoundation: 'Close-up detail of the smooth turned dished teak rim and solid brass underside connecting boss on the Tarang table.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Veda Dining Table
  {
    id: 'img-veda-hero',
    category: 'product',
    productSlug: 'veda-dining-table',
    fileName: 'veda_dining_table_hero.png',
    filePath: '/images/products/veda_dining_table_hero.png',
    role: 'Veda Dining Table Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Veda Trestle Dining Table in solid teakwood set for six in a warm contemporary dining room',
    promptFoundation: 'Product photography of a 6-seater solid teakwood trestle dining table, 38mm solid timber tabletop with chamfered edge, sculptural trestle base with traditional through-tenon wedge joinery, warm studio daylight.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-veda-trestle',
    category: 'product',
    productSlug: 'veda-dining-table',
    fileName: 'veda_dining_table_trestle.png',
    filePath: '/images/products/veda_dining_table_trestle.png',
    role: 'Veda Trestle Joinery View',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Perspective showing the solid teak trestle base and through-tenon wedge joinery of Veda Table',
    promptFoundation: 'Low-angle perspective showing the substantial solid teak trestle legs and the central timber stretcher with exposed wedge pin.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-veda-detail',
    category: 'product',
    productSlug: 'veda-dining-table',
    fileName: 'veda_dining_table_detail.png',
    filePath: '/images/products/veda_dining_table_detail.png',
    role: 'Veda Tabletop Edge Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up detail of 38mm solid teak tabletop chamfered edge on Veda Dining Table',
    promptFoundation: 'Macro detail of 38mm solid seasoned teak dining table edge, showing straight wood grain, soft chamfer, and natural matte oil finish.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Dhyaan Dining Chair
  {
    id: 'img-dhyaan-hero',
    category: 'product',
    productSlug: 'dhyaan-dining-chair',
    fileName: 'dhyaan_dining_chair_hero.png',
    filePath: '/images/products/dhyaan_dining_chair_hero.png',
    role: 'Dhyaan Chair Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Dhyaan Spindle Dining Chair in solid teakwood with steam-bent backrest',
    promptFoundation: 'Commercial studio product shot of a contemporary solid teak spindle dining chair, continuous steam-bent curved top rail, hand-carved saddle seat, splayed tapered legs, clean neutral background.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-dhyaan-pair',
    category: 'product',
    productSlug: 'dhyaan-dining-chair',
    fileName: 'dhyaan_dining_chair_pair.png',
    filePath: '/images/products/dhyaan_dining_chair_pair.png',
    role: 'Dhyaan Chair Pair View',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Pair of Dhyaan Dining Chairs tucked alongside a natural wood dining table',
    promptFoundation: 'Pair of solid teak Dhyaan spindle dining chairs arranged casually beside the edge of a wooden dining table.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-dhyaan-detail',
    category: 'product',
    productSlug: 'dhyaan-dining-chair',
    fileName: 'dhyaan_dining_chair_detail.png',
    filePath: '/images/products/dhyaan_dining_chair_detail.png',
    role: 'Dhyaan Spindle Joinery Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro shot of spindle joinery and curved backrail on Dhyaan Dining Chair',
    promptFoundation: 'Macro photography of the steam-bent backrail joint where delicate vertical wooden spindles insert seamlessly into the top rail.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Kosh Sideboard
  {
    id: 'img-kosh-hero',
    category: 'product',
    productSlug: 'kosh-sideboard',
    fileName: 'kosh_sideboard_hero.png',
    filePath: '/images/products/kosh_sideboard_hero.png',
    role: 'Kosh Sideboard Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Kosh Slatted Credenza in natural teak with brass pulls and sliding tambour doors',
    promptFoundation: 'Product photography of a low architectural credenza sideboard, 160cm wide, natural teak veneer and solid frame, fine vertical slatted sliding tambour doors, brushed solid brass round door pulls, clean studio lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-kosh-open',
    category: 'product',
    productSlug: 'kosh-sideboard',
    fileName: 'kosh_sideboard_open.png',
    filePath: '/images/products/kosh_sideboard_open.png',
    role: 'Kosh Sideboard Open Door View',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Kosh Credenza with one tambour door open revealing spacious internal wood shelving',
    promptFoundation: 'Kosh credenza with one slatted tambour door slid open, revealing adjustable interior solid wood shelving with neatly organized ceramic bowls.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-kosh-detail',
    category: 'product',
    productSlug: 'kosh-sideboard',
    fileName: 'kosh_sideboard_detail.png',
    filePath: '/images/products/kosh_sideboard_detail.png',
    role: 'Kosh Brass Pull Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Detail of brushed brass handle and fluted teak slats on Kosh Credenza',
    promptFoundation: 'Extreme macro detail of a brushed solid brass door pull knob mounted on the finely milled vertical teak timber slats of the Kosh credenza.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Sopan Shelving Unit
  {
    id: 'img-sopan-hero',
    category: 'product',
    productSlug: 'sopan-shelving-unit',
    fileName: 'sopan_shelving_unit_hero.png',
    filePath: '/images/products/sopan_shelving_unit_hero.png',
    role: 'Sopan Shelving Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Sopan Open Modular Shelving unit with solid teak uprights and charcoal steel shelves',
    promptFoundation: 'Product photography of an open 5-tier modular shelving unit (180cm tall), solid vertical teakwood upright columns, laser-cut folded matte charcoal steel shelf trays, clean neutral background.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sopan-styled',
    category: 'product',
    productSlug: 'sopan-shelving-unit',
    fileName: 'sopan_shelving_unit_styled.png',
    filePath: '/images/products/sopan_shelving_unit_styled.png',
    role: 'Sopan Shelving Styled View',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Sopan Shelving styled with art books, ceramic pots, and small indoor plants in a study',
    promptFoundation: 'Sopan open shelving unit styled thoughtfully with architecture books, handmade ceramic pottery, and a small trailing pothos plant in an airy modern interior.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-sopan-detail',
    category: 'product',
    productSlug: 'sopan-shelving-unit',
    fileName: 'sopan_shelving_unit_detail.png',
    filePath: '/images/products/sopan_shelving_unit_detail.png',
    role: 'Sopan Steel-Teak Joint Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up of teak column joint and folded matte steel shelf lip on Sopan Unit',
    promptFoundation: 'Macro detail showing the interlocking joint between the CNC-machined solid teak column upright and the folded charcoal powder-coated steel shelf tray.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Nidra Platform Bed
  {
    id: 'img-nidra-hero',
    category: 'product',
    productSlug: 'nidra-platform-bed',
    fileName: 'nidra_platform_bed_hero.png',
    filePath: '/images/products/nidra_platform_bed_hero.png',
    role: 'Nidra Platform Bed Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Nidra Low Platform Bed in solid teakwood with oatmeal linen headboard in a calm bedroom',
    promptFoundation: 'Commercial studio product photography of a low-profile king-size platform bed, floating solid teakwood frame, upholstered oatmeal linen cushioned headboard, crisp neutral bed linens, soft morning light.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-nidra-angle',
    category: 'product',
    productSlug: 'nidra-platform-bed',
    fileName: 'nidra_platform_bed_angle.png',
    filePath: '/images/products/nidra_platform_bed_angle.png',
    role: 'Nidra Platform Bed Floating Plinth Angle',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Three-quarter angle showing floating plinth base of Nidra Platform Bed',
    promptFoundation: 'Low three-quarter perspective highlighting the recessed plinth underneath the Nidra solid teak bed that creates a floating architectural silhouette.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-nidra-detail',
    category: 'product',
    productSlug: 'nidra-platform-bed',
    fileName: 'nidra_platform_bed_detail.png',
    filePath: '/images/products/nidra_platform_bed_detail.png',
    role: 'Nidra Teak Corner & Linen Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro shot of solid teak corner joinery and oatmeal headboard fabric on Nidra Bed',
    promptFoundation: 'Macro shot of rounded solid teak corner rail joinery meeting the tailored oatmeal linen fabric on the Nidra bed headboard.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Aksh Floor Lamp
  {
    id: 'img-aksh-hero',
    category: 'product',
    productSlug: 'aksh-floor-lamp',
    fileName: 'aksh_floor_lamp_hero.png',
    filePath: '/images/products/aksh_floor_lamp_hero.png',
    role: 'Aksh Floor Lamp Hero',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Aksh Floor Lamp with turned teak stem and spun brass base casting warm light',
    promptFoundation: 'Product photography of an architectural floor lamp (145cm tall), spun solid brass base, slender lathe-turned solid teak column, natural woven linen cylindrical shade, clean studio background.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-aksh-ambient',
    category: 'product',
    productSlug: 'aksh-floor-lamp',
    fileName: 'aksh_floor_lamp_ambient.png',
    filePath: '/images/products/aksh_floor_lamp_ambient.png',
    role: 'Aksh Floor Lamp Ambient Glow',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Aksh Floor Lamp glowing warmly in an evening living room corner',
    promptFoundation: 'Evening interior setting with the Aksh floor lamp illuminated, casting a soft 2700K golden halo against a mineral lime-wash wall.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-aksh-detail',
    category: 'product',
    productSlug: 'aksh-floor-lamp',
    fileName: 'aksh_floor_lamp_detail.png',
    filePath: '/images/products/aksh_floor_lamp_detail.png',
    role: 'Aksh Brass Base & Switch Detail',
    dimensions: { width: 1600, height: 1200 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up of spun brass ferrule and turned teak grain on Aksh Lamp',
    promptFoundation: 'Macro close-up of hand-spun solid brass base disc, braided jute power cord, and solid brass step switch on hardwood flooring.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Materials Macro
  {
    id: 'img-mat-teak',
    category: 'material',
    fileName: 'macro_teak_wood_grain.png',
    filePath: '/images/materials/macro_teak_wood_grain.png',
    role: 'Seasoned Indian Teakwood Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up macro detail of seasoned Indian teakwood grain with natural matte oil finish',
    promptFoundation: 'Macro photography of seasoned Indian teak wood grain, straight golden-brown grain with subtle natural pores, matte silky organic oil finish.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-mat-walnut',
    category: 'material',
    fileName: 'macro_walnut_wood_grain.png',
    filePath: '/images/materials/macro_walnut_wood_grain.png',
    role: 'Solid American Walnut Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro texture of solid walnut wood grain showing rich dark tones and smooth finish',
    promptFoundation: 'Macro photograph of deep chocolate American walnut timber grain, subtle undulating grain lines, smooth silky matte texture.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-mat-boucle',
    category: 'material',
    fileName: 'macro_boucle_textile.png',
    filePath: '/images/materials/macro_boucle_textile.png',
    role: 'Architectural Moss Bouclé Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro photograph of muted moss looped bouclé textile weave',
    promptFoundation: 'Extreme macro photography of muted moss green looped bouclé upholstery fabric, rich dimensional curly texture, soft tactile lighting.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-mat-linen',
    category: 'material',
    fileName: 'macro_linen_cotton.png',
    filePath: '/images/materials/macro_linen_cotton.png',
    role: 'Oatmeal Linen-Cotton Slub Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro photograph of oatmeal natural linen-cotton slub fabric weave',
    promptFoundation: 'Macro close-up of natural oatmeal linen-cotton slub textile weave, crisp natural yarn texture, subtle organic slub irregularities.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-mat-stone',
    category: 'material',
    fileName: 'macro_sandstone_texture.png',
    filePath: '/images/materials/macro_sandstone_texture.png',
    role: 'Honed Dholpur Sandstone Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Macro texture of honed Dholpur beige sandstone surface with delicate mineral grain',
    promptFoundation: 'Macro photograph of honed beige Indian Dholpur sandstone surface, smooth matte texture with tiny warm quartz mineral flecks.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-mat-brass',
    category: 'material',
    fileName: 'macro_brushed_brass.png',
    filePath: '/images/materials/macro_brushed_brass.png',
    role: 'Brushed Solid Brass Macro',
    dimensions: { width: 1200, height: 900 },
    aspectRatio: '4:3',
    focalPoint: 'Center',
    alt: 'Close-up macro of satin brushed solid brass surface with golden warm reflections',
    promptFoundation: 'Macro photography of solid brushed brass metal surface, fine linear brush strokes, warm golden luster, soft ambient highlight.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Studio & Craftsmanship
  {
    id: 'img-studio-joinery',
    category: 'studio',
    fileName: 'studio_craftsman_joinery.png',
    filePath: '/images/studio/studio_craftsman_joinery.png',
    role: 'Craftsman Bench Joinery',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Master woodworker precisely chiseling a mortise-and-tenon teakwood joint in our Ahmedabad workshop',
    promptFoundation: 'Editorial documentary photography inside a serene Indian woodworking workshop in Ahmedabad, master artisan hand-chiseling a mortise-and-tenon solid teakwood joint, wood shavings on workbench, natural window light, focused craftsmanship.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  {
    id: 'img-studio-workshop',
    category: 'studio',
    fileName: 'studio_workshop_atmosphere.png',
    filePath: '/images/studio/studio_workshop_atmosphere.png',
    role: 'Workshop Architecture & Stacks',
    dimensions: { width: 1600, height: 1067 },
    aspectRatio: '3:2',
    focalPoint: 'Center',
    alt: 'Sunlit timber workshop with neatly stacked seasoned Indian teak planks and furniture frames in progress',
    promptFoundation: 'Wide architectural photograph of an organized sunlit furniture workshop in India, seasoned teak planks stacked to dry, clean joinery benches, calm sawdust-dusted atmosphere, high steel truss roof.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
  // Social / OG
  {
    id: 'img-og-share',
    category: 'social',
    fileName: 'og_niyata_living.png',
    filePath: '/images/social/og_niyata_living.png',
    role: 'OpenGraph & Twitter Share Card',
    dimensions: { width: 1200, height: 630 },
    aspectRatio: '1.91:1',
    focalPoint: 'Center',
    alt: 'Niyata Living — Contemporary Indian Furniture Commerce Experience',
    promptFoundation: 'Architectural composition of contemporary Indian teak living room furniture against a warm lime plaster wall, clean modern typography framing, calm morning daylight.',
    reviewStatus: 'Approved',
    isIllustrative: true,
  },
];
