import { Product } from '@/types/product';

export const PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    slug: 'prana-modular-sofa',
    name: 'Prana Modular Sofa',
    tagline: 'Architectural low-profile modular seating engineered for urban Indian living rooms.',
    description:
      'The Prana Modular Sofa is Niyata’s flagship seating system. Built on a low-slung, kiln-seasoned solid Indian teak plinth, it balances deep, supportive ergonomics with breathable proportions that prevent smaller living rooms from feeling visually crowded.',
    detailedStory:
      'Designed around the realities of Indian apartment living, Prana addresses dust clearance, ventilation, and family longevity. Its modular components lock effortlessly with concealed steel bayonet connectors, enabling seamless transition between compact 2-seat, generous 3-seat, and relaxed left/right chaise configurations. The upholstery is crafted from high-durability textured weaves that resist humidity and daily wear.',
    category: 'seating',
    categoryLabel: 'Seating',
    roomCategories: ['living'],
    roomLabels: ['Living Room'],
    priceINR: 68900,
    priceRange: {
      minINR: 54900,
      maxINR: 84900,
    },
    primaryMaterial: 'Solid Teak',
    materialsList: [
      'Kiln-seasoned Solid Indian Teakwood Plinth & Legs',
      'Dual-Density High-Resilience PU Foam with Feather-Touch Fiber Wrap',
      'Heavyweight 480 GSM Cotton-Linen or Bouclé Upholstery',
      'Concealed German Steel Bayonet Connectors',
    ],
    colors: [
      { name: 'Oatmeal Natural', code: 'oat', hex: '#D6CEBE', materialName: 'Linen-Cotton Weave' },
      { name: 'Muted Moss', code: 'moss', hex: '#5E6D55', materialName: 'Architectural Bouclé' },
      { name: 'Warm Terracotta Clay', code: 'clay', hex: '#B8684D', materialName: 'Tactile Flatweave' },
    ],
    dimensions: {
      widthCm: 240,
      depthCm: 90,
      heightCm: 78,
      seatHeightCm: 42,
      clearanceCm: 14,
      weightKg: 68,
      formatted: '240 × 90 × 78 cm (3-Seat Standard)',
    },
    constructionDetails: [
      'Mortise and tenon internal hardwood frame with reinforced corner blocks.',
      'Sinuous high-tensile spring suspension with reinforced jute webbing.',
      '14 cm elevated clearance facilitates automated vacuum and traditional floor cleaning.',
      'Removable, dry-cleanable cushion covers with concealed YKK metal zippers.',
    ],
    careInstructions: [
      'Vacuum weekly using a soft upholstery brush attachment on low suction.',
      'Promptly blot liquid spills with an undyed dry cloth; do not rub.',
      'Rotate and fluff seat and back cushions bi-weekly to maintain loft.',
      'Keep away from direct unshaded afternoon sunlight to preserve fabric tone.',
    ],
    assemblyInfo: {
      required: true,
      level: 'White-Glove Assembly Provided',
      estimatedMinutes: 20,
      instructions:
        'Delivered in modular modules. Our delivery team unboxes, connects the steel bayonet couplings, levels the teak plinth, and removes all protective packaging.',
    },
    spatialSuitability:
      'Ideal for 2 BHK and 3 BHK living rooms. The 14cm under-sofa clearance maintains visual light and floor continuity.',
    isFlagshipConfigurable: true,
    sofaLayouts: [
      {
        id: '2-seat',
        name: '2-Seat Compact',
        description: 'Two spacious seating bays ideal for urban 1 BHK & 2 BHK living areas.',
        dimensionsCm: '180 × 90 × 78 cm',
        priceINR: 54900,
        widthCm: 180,
        depthCm: 90,
        heightCm: 78,
      },
      {
        id: '3-seat',
        name: '3-Seat Standard',
        description: 'Our most balanced footprint for contemporary Indian family apartments.',
        dimensionsCm: '240 × 90 × 78 cm',
        priceINR: 68900,
        widthCm: 240,
        depthCm: 90,
        heightCm: 78,
      },
      {
        id: 'chaise',
        name: '3-Seat with Extended Chaise',
        description: 'Generous lounge module for extended resting and evening reading.',
        dimensionsCm: '270 × 160 × 78 cm',
        priceINR: 84900,
        widthCm: 270,
        depthCm: 160,
        heightCm: 78,
      },
    ],
    sofaFabrics: [
      {
        id: 'oat',
        name: 'Oat Natural',
        toneDescription: 'Warm mineral linen-cotton blend with subtle natural slub',
        hex: '#D6CEBE',
        composition: '65% Cotton, 35% Linen (480 GSM)',
      },
      {
        id: 'moss',
        name: 'Muted Moss',
        toneDescription: 'Deep architectural olive woven bouclé with tactile depth',
        hex: '#5E6D55',
        composition: '70% Polyester Wool-Blend, 30% Cotton (520 GSM)',
      },
      {
        id: 'clay',
        name: 'Terracotta Clay',
        toneDescription: 'Warm earthy mineral flatweave inspired by baked Indian pottery',
        hex: '#B8684D',
        composition: '80% Cotton, 20% Linen (460 GSM)',
      },
    ],
    featured: true,
    leadTimeWeeks: 3,
    origin: 'Crafted in Ahmedabad, India',
    images: [
      {
        id: 'prana-hero-3seat-oat',
        src: '/images/products/prana_sofa_3seat_oat.png',
        alt: 'Prana 3-Seat Modular Sofa in Oat Natural upholstery on solid teak base',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
        layoutId: '3-seat',
        fabricId: 'oat',
      },
      {
        id: 'prana-config-2seat-oat',
        src: '/images/products/prana_sofa_2seat_oat.png',
        alt: 'Prana 2-Seat Compact Modular Sofa in Oat Natural fabric',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '2-seat',
        fabricId: 'oat',
      },
      {
        id: 'prana-config-2seat-moss',
        src: '/images/products/prana_sofa_2seat_moss.png',
        alt: 'Prana 2-Seat Compact Modular Sofa in Muted Moss bouclé',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '2-seat',
        fabricId: 'moss',
      },
      {
        id: 'prana-config-2seat-clay',
        src: '/images/products/prana_sofa_2seat_clay.png',
        alt: 'Prana 2-Seat Compact Modular Sofa in Terracotta Clay flatweave',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '2-seat',
        fabricId: 'clay',
      },
      {
        id: 'prana-config-3seat-oat',
        src: '/images/products/prana_sofa_3seat_oat.png',
        alt: 'Prana 3-Seat Standard Modular Sofa in Oat Natural fabric',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '3-seat',
        fabricId: 'oat',
      },
      {
        id: 'prana-config-3seat-moss',
        src: '/images/products/prana_sofa_3seat_moss.png',
        alt: 'Prana 3-Seat Standard Modular Sofa in Muted Moss bouclé',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '3-seat',
        fabricId: 'moss',
      },
      {
        id: 'prana-config-3seat-clay',
        src: '/images/products/prana_sofa_3seat_clay.png',
        alt: 'Prana 3-Seat Standard Modular Sofa in Terracotta Clay flatweave',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: '3-seat',
        fabricId: 'clay',
      },
      {
        id: 'prana-config-chaise-oat',
        src: '/images/products/prana_sofa_chaise_oat.png',
        alt: 'Prana Chaise Modular Sofa in Oat Natural fabric',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: 'chaise',
        fabricId: 'oat',
      },
      {
        id: 'prana-config-chaise-moss',
        src: '/images/products/prana_sofa_chaise_moss.png',
        alt: 'Prana Chaise Modular Sofa in Muted Moss bouclé',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: 'chaise',
        fabricId: 'moss',
      },
      {
        id: 'prana-config-chaise-clay',
        src: '/images/products/prana_sofa_chaise_clay.png',
        alt: 'Prana Chaise Modular Sofa in Terracotta Clay flatweave',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'configurator',
        layoutId: 'chaise',
        fabricId: 'clay',
      },
      {
        id: 'prana-detail-joinery',
        src: '/images/products/prana_sofa_detail_joinery.png',
        alt: 'Prana Sofa solid teak plinth joinery and fabric detail',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-02',
    slug: 'kaya-lounge-chair',
    name: 'Kaya Low Lounge Chair',
    tagline: 'Sculptural comfort with a pitched solid teak frame and relaxed linen sling.',
    description:
      'The Kaya Lounge Chair combines architectural poise with deeply relaxed ergonomics. Its angled teak silhouette offers an inviting 105-degree recline, making it the perfect sanctuary for weekend reading or intimate living room conversations.',
    detailedStory:
      'Handcrafted from sustainable Central Indian teakwood, Kaya celebrates honest exposed joinery with soft, hand-radiused edges. The floating sling seat is upholstered in breathable Belgian-Indian linen blend over high-density foam, ensuring lasting structural memory without sagging.',
    category: 'seating',
    categoryLabel: 'Seating',
    roomCategories: ['living', 'study', 'bedroom'],
    roomLabels: ['Living Room', 'Study', 'Bedroom'],
    priceINR: 18900,
    primaryMaterial: 'Solid Teak',
    materialsList: [
      'FSC-Grade Seasoned Indian Teakwood with Matte Oil Finish',
      'Dual-Layer High-Resilience Molded Cushioning',
      '420 GSM Textured Linen-Cotton Sling Upholstery',
      'Solid Brass Hardware Accents',
    ],
    colors: [
      { name: 'Mineral Sand', code: 'sand', hex: '#DCD4C5', materialName: 'Linen Weave' },
      { name: 'Olive Drab', code: 'olive', hex: '#636B58', materialName: 'Cotton Twill' },
      { name: 'Charcoal Slub', code: 'charcoal', hex: '#2A2927', materialName: 'Linen Blend' },
    ],
    dimensions: {
      widthCm: 76,
      depthCm: 82,
      heightCm: 72,
      seatHeightCm: 38,
      clearanceCm: 22,
      weightKg: 16,
      formatted: '76 × 82 × 72 cm',
    },
    constructionDetails: [
      'Bridle joinery along the backrest junction with exposed timber dowels.',
      'Slightly pitched 105-degree resting geometry for lumbar support.',
      'Hand-applied organic wax oil finish that highlights the authentic teak grain.',
    ],
    careInstructions: [
      'Dust the wood frame weekly with a dry microfibre cloth.',
      'Reapply natural beeswax polish once annually to nourish the teak.',
      'Spot clean linen cushions with mild, pH-neutral textile cleaner.',
    ],
    assemblyInfo: {
      required: false,
      level: 'None (Fully Assembled)',
      estimatedMinutes: 0,
      instructions: 'Arrives fully assembled and ready for placement in your living space.',
    },
    spatialSuitability:
      'Compact footprint suits cozy corners, reading nooks, or paired opposite the Prana sofa.',
    featured: true,
    leadTimeWeeks: 2,
    origin: 'Handmade in Jodhpur, India',
    images: [
      {
        id: 'kaya-hero',
        src: '/images/products/kaya_lounge_chair_hero.png',
        alt: 'Kaya Low Lounge Chair in solid teakwood with mineral sand linen upholstery',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'kaya-side',
        src: '/images/products/kaya_lounge_chair_side.png',
        alt: 'Side profile of Kaya Lounge Chair showing angled ergonomic teak frame',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'kaya-detail',
        src: '/images/products/kaya_lounge_chair_detail.png',
        alt: 'Close-up detail of bridle wood joinery and textured linen weave on Kaya Chair',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-03',
    slug: 'setu-bench',
    name: 'Setu Upholstered Bench',
    tagline: 'Versatile transitional seating with solid walnut legs and textured bouclé cushion.',
    description:
      'Setu (meaning bridge) effortlessly connects living, entryway, and bedroom environments. With clean architectural lines and an invitingly cushioned top, it functions as casual seating, an end-of-bed bench, or a sleek foyer landing pad.',
    detailedStory:
      'Precision-milled from solid American walnut, the Setu bench features subtle brass accent collars where the tapered cylindrical legs meet the base frame. The firmly tailored bouclé top provides lasting comfort for dressing or entertaining.',
    category: 'seating',
    categoryLabel: 'Seating',
    roomCategories: ['bedroom', 'living', 'entryway'],
    roomLabels: ['Bedroom', 'Living Room', 'Entryway'],
    priceINR: 12900,
    primaryMaterial: 'Solid Walnut',
    materialsList: [
      'Solid Walnut Timber Frame with Natural Satin Luster',
      'Textured Bouclé Upholstery with Anti-Pilling Treatment',
      'Solid Spun Brass Leg Ferrules',
      'High-Density 40D Foam Core',
    ],
    colors: [
      { name: 'Warm Cream', code: 'cream', hex: '#F0EBE1', materialName: 'Bouclé Weave' },
      { name: 'Basalt Charcoal', code: 'basalt', hex: '#33312E', materialName: 'Bouclé Weave' },
    ],
    dimensions: {
      widthCm: 120,
      depthCm: 40,
      heightCm: 44,
      seatHeightCm: 44,
      clearanceCm: 32,
      weightKg: 12,
      formatted: '120 × 40 × 44 cm',
    },
    constructionDetails: [
      'Mortise and tenon timber substructure with internal steel gussets.',
      'Precision brass ferrules provide protection against floor moisture during mopping.',
      'Generous 32cm floor clearance ensures open airy space perception.',
    ],
    careInstructions: [
      'Gently dab fabric with a damp white towel for spot cleaning.',
      'Wipe walnut legs with a soft cotton cloth.',
    ],
    assemblyInfo: {
      required: true,
      level: 'Simple (Leg Attachment)',
      estimatedMinutes: 5,
      instructions: 'Thread the 4 tapered walnut legs into the pre-installed steel threaded plates. Tool included.',
    },
    spatialSuitability: 'Perfect at the foot of king and queen beds, or along narrow apartment corridors.',
    featured: false,
    leadTimeWeeks: 2,
    origin: 'Crafted in Bengaluru, India',
    images: [
      {
        id: 'setu-hero',
        src: '/images/products/setu_bench_hero.png',
        alt: 'Setu Upholstered Bench with cream bouclé cushion and solid walnut legs with brass accents',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'setu-room',
        src: '/images/products/setu_bench_room.png',
        alt: 'Setu Bench positioned at the foot of the Nidra Platform Bed',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'setu-detail',
        src: '/images/products/setu_bench_detail.png',
        alt: 'Macro detail of Setu Bench brass ferrule and bouclé fabric',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-04',
    slug: 'aalap-coffee-table',
    name: 'Aalap Fluted Coffee Table',
    tagline: 'Grounded architectural presence featuring a fluted solid teak base and honed sandstone top.',
    description:
      'The Aalap Coffee Table is an exploration in texture and weight. Its cylindrical fluted base in dark-seasoned teak supports a subtly bevelled slab of natural honed Dholpur sandstone, bringing geological serenity to the center of the room.',
    detailedStory:
      'Hand-carved fluting around the cylindrical teak pedestal creates an ever-shifting rhythm of light and shadow throughout the day. The sandstone top is hand-honed and sealed with an invisible hydrophobic nano-barrier, safeguarding the porous natural stone against tea and coffee stains.',
    category: 'tables',
    categoryLabel: 'Tables',
    roomCategories: ['living'],
    roomLabels: ['Living Room'],
    priceINR: 14900,
    primaryMaterial: 'Natural Stone',
    materialsList: [
      'Honed Dholpur Beige Sandstone Top with Chamfered Perimeter',
      'Fluted Solid Indian Teak Wood Pedestal Base',
      'Concealed Internal Structural Steel Counterweight',
      'Food-Safe Matte Hydrophobic Stone Sealant',
    ],
    colors: [
      { name: 'Warm Dholpur Sandstone & Natural Teak', code: 'teak-stone', hex: '#D2C3AA', materialName: 'Honed Stone / Teak' },
      { name: 'Basalt Grey Stone & Dark Walnut', code: 'walnut-stone', hex: '#635A4F', materialName: 'Grey Sandstone / Walnut' },
    ],
    dimensions: {
      widthCm: 90,
      depthCm: 90,
      heightCm: 38,
      weightKg: 34,
      formatted: '90 × 90 × 38 cm',
    },
    constructionDetails: [
      'Individually milled solid teak flutes bonded around a rigid birch ply internal drum.',
      'Precision machined steel sub-plate anchors the heavy stone top securely.',
      'Integrated acoustic felt pads under the base protect delicate floor tiles.',
    ],
    careInstructions: [
      'Use coasters for hot beverages and citrus drinks.',
      'Clean stone surface with warm water and mild dish soap; avoid acidic or abrasive chemicals.',
      'Re-seal stone top every 2 years with standard natural stone impregnator.',
    ],
    assemblyInfo: {
      required: true,
      level: 'Simple (Leg Attachment)',
      estimatedMinutes: 10,
      instructions: 'Place the fluted pedestal in position. Lower the pre-sealed stone top onto the interlocking steel sub-plate.',
    },
    spatialSuitability: 'Circular form factor promotes fluid walking paths in both square and narrow living rooms.',
    featured: true,
    leadTimeWeeks: 3,
    origin: 'Crafted in Jaipur & Ahmedabad, India',
    images: [
      {
        id: 'aalap-hero',
        src: '/images/products/aalap_coffee_table_hero.png',
        alt: 'Aalap Fluted Coffee Table with honed sandstone top and solid teak fluted pedestal',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'aalap-top',
        src: '/images/products/aalap_coffee_table_top.png',
        alt: 'Top-down three-quarter perspective of Aalap Coffee Table showing sandstone grain',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'aalap-detail',
        src: '/images/products/aalap_coffee_table_detail.png',
        alt: 'Close-up of hand-milled teak fluting and chamfered sandstone rim on Aalap Table',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-05',
    slug: 'tarang-side-table',
    name: 'Tarang Nesting Side Table',
    tagline: 'Lightweight side companion with turned teakwood top and slender powder-coated steel tripod legs.',
    description:
      'Tarang offers versatile, effortless mobility beside the sofa or bed. With a gently dished solid teak tabletop and slender matte charcoal steel legs, it catches keys, a brass chai glass, or your evening book without dominating floor area.',
    detailedStory:
      'Lathe-turned from a single blank of seasoned teak, the tabletop features a subtle 8mm raised lip that prevents items from rolling off. The minimalist tripod base is engineered from welded solid steel rod finished in a tactile matte architectural powder coat.',
    category: 'tables',
    categoryLabel: 'Tables',
    roomCategories: ['living', 'bedroom', 'study'],
    roomLabels: ['Living Room', 'Bedroom', 'Study'],
    priceINR: 7900,
    primaryMaterial: 'Solid Teak',
    materialsList: [
      'Lathe-Turned Solid Indian Teakwood Top with Raised Rim',
      'Matte Fine-Texture Powder-Coated Steel Tripod Base',
      'Solid Brass Threaded Countersunk Fasteners',
    ],
    colors: [
      { name: 'Natural Teak & Charcoal Black', code: 'teak-black', hex: '#9E6D38', materialName: 'Teak / Steel' },
      { name: 'Smoked Teak & Muted Sage', code: 'smoked-sage', hex: '#588157', materialName: 'Smoked Teak / Steel' },
    ],
    dimensions: {
      widthCm: 42,
      depthCm: 42,
      heightCm: 50,
      clearanceCm: 46,
      weightKg: 5,
      formatted: '42 × 42 × 50 cm',
    },
    constructionDetails: [
      'Turned perimeter rim acts as an organic catch-all tray.',
      'Slightly splayed tripod footprint provides stable 3-point balance on any uneven floor.',
      'Brass connecting puck provides an elegant material break between wood and metal.',
    ],
    careInstructions: [
      'Wipe down with a soft damp cloth.',
      'Avoid placing dripping wet cups directly on unsealed wood without coasters.',
    ],
    assemblyInfo: {
      required: true,
      level: 'Simple (Leg Attachment)',
      estimatedMinutes: 5,
      instructions: 'Screw the 3 steel tripod legs into the central brass underside boss by hand. No tools required.',
    },
    spatialSuitability: 'Tucks snugly beside deep sofas or next to low platform beds.',
    featured: false,
    leadTimeWeeks: 1,
    origin: 'Crafted in Ahmedabad, India',
    images: [
      {
        id: 'tarang-hero',
        src: '/images/products/tarang_side_table_hero.png',
        alt: 'Tarang Side Table with turned teak dished top and black tripod steel legs',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'tarang-angle',
        src: '/images/products/tarang_side_table_angle.png',
        alt: 'Three-quarter ambient view of Tarang Side Table beside a lounge chair',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'tarang-detail',
        src: '/images/products/tarang_side_table_detail.png',
        alt: 'Detail of dished teak rim and brass connection on Tarang Side Table',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-06',
    slug: 'veda-dining-table',
    name: 'Veda Trestle Dining Table',
    tagline: 'Commanding 6-seater dining centerpiece celebrating traditional mortise-and-tenon timber joinery.',
    description:
      'The Veda Dining Table is built to host decades of celebratory Indian family feasts and quiet morning chai. Its substantial 38mm solid teak tabletop rests on an architectural trestle base, maximizing legroom on all sides without corner leg obstructions.',
    detailedStory:
      'Constructed exclusively from Grade-A seasoned Indian teak, Veda honors timeless woodcraft. The trestle stretcher is locked with a traditional through-tenon wedge joint. The wood is protected with a zero-VOC food-safe matte ceramic oil finish that repels turmeric, ghee, and wine while keeping the natural tactile warmth of raw timber.',
    category: 'tables',
    categoryLabel: 'Tables',
    roomCategories: ['dining'],
    roomLabels: ['Dining Room'],
    priceINR: 39900,
    primaryMaterial: 'Solid Teak',
    materialsList: [
      '100% Solid Kiln-Seasoned Indian Teakwood (38mm Top Thickness)',
      'Traditional Hardwood Wedge-Key Trestle Stretcher',
      'Food-Safe Matte Polyurethane & Ceramic Micro-Oil Sealant',
    ],
    colors: [
      { name: 'Raw Honey Teak', code: 'honey-teak', hex: '#A87948', materialName: 'Solid Teak' },
      { name: 'Heritage Dark Teak', code: 'heritage-teak', hex: '#634423', materialName: 'Solid Teak' },
    ],
    dimensions: {
      widthCm: 180,
      depthCm: 90,
      heightCm: 76,
      clearanceCm: 72,
      weightKg: 52,
      formatted: '180 × 90 × 76 cm (6-Seater)',
    },
    constructionDetails: [
      'Full mortise and tenon joinery throughout with pinned timber dowels.',
      'Underside relief slots and steel C-channels prevent cross-grain seasonal warping.',
      'Trestle architecture allows 6 to 8 chairs to tuck in completely without knee clashes.',
    ],
    careInstructions: [
      'Wipe clean after meals with a warm, damp microfibre cloth.',
      'Promptly wipe spills containing curry, turmeric, or oil.',
      'Use hot pads or trivets for vessels taken straight from the stove.',
    ],
    assemblyInfo: {
      required: true,
      level: 'White-Glove Assembly Provided',
      estimatedMinutes: 25,
      instructions:
        'Assembled on-site by our logistics team. Trestle leg assemblies are positioned and secured with heavy-duty hidden steel bolts and hardwood wedges.',
    },
    spatialSuitability: 'Comfortably seats 6 adults in standard 10 × 12 ft urban dining spaces.',
    featured: true,
    leadTimeWeeks: 4,
    origin: 'Crafted in Jodhpur & Surat, India',
    images: [
      {
        id: 'veda-hero',
        src: '/images/products/veda_dining_table_hero.png',
        alt: 'Veda Trestle Dining Table in solid teakwood set for six in a warm contemporary dining room',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'veda-trestle',
        src: '/images/products/veda_dining_table_trestle.png',
        alt: 'Perspective showing the solid teak trestle base and through-tenon wedge joinery of Veda Table',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'veda-detail',
        src: '/images/products/veda_dining_table_detail.png',
        alt: 'Close-up detail of 38mm solid teak tabletop chamfered edge on Veda Dining Table',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-07',
    slug: 'dhyaan-dining-chair',
    name: 'Dhyaan Spindle Dining Chair',
    tagline: 'Ergonomically steam-bent teak dining chair with sculptural spindle back and sculpted saddle seat.',
    description:
      'The Dhyaan Dining Chair refines the classic spindle chair into a contemporary Indian architectural icon. Its steam-bent continuous curved top rail cradles the spine, while the dished solid teak saddle seat ensures comfort throughout long dinner parties.',
    detailedStory:
      'Every spindle on the Dhyaan chair is individually hand-shaped and pegged into the solid seat pan. The legs feature subtle outward splay for high dynamic stability, and are braced with low-profile stretchers that double as discreet footrests.',
    category: 'seating',
    categoryLabel: 'Seating',
    roomCategories: ['dining', 'study'],
    roomLabels: ['Dining Room', 'Study'],
    priceINR: 8900,
    primaryMaterial: 'Solid Teak',
    materialsList: [
      'Solid Indian Teak with Steam-Bent Backrest Rail',
      'Hand-Sculpted Ergonomic Saddle Seat',
      'Tenon-and-Mortise Spindle Joints',
    ],
    colors: [
      { name: 'Natural Warm Teak', code: 'natural-teak', hex: '#9E6D38', materialName: 'Solid Teak' },
      { name: 'Ebonized Matte Charcoal', code: 'ebonized', hex: '#22201E', materialName: 'Stained Teak' },
    ],
    dimensions: {
      widthCm: 48,
      depthCm: 52,
      heightCm: 80,
      seatHeightCm: 45,
      weightKg: 6.5,
      formatted: '48 × 52 × 80 cm',
    },
    constructionDetails: [
      'Continuous steam-bent top rail without glue joints for exceptional torsional strength.',
      'Dished saddle seat relieves pressure points without requiring foam upholstery.',
      'Protective non-marring floor glides pre-installed on all four leg tips.',
    ],
    careInstructions: [
      'Dust regularly with a dry soft cloth.',
      'Clean food splatters immediately with a damp cloth; dry thoroughly.',
    ],
    assemblyInfo: {
      required: false,
      level: 'None (Fully Assembled)',
      estimatedMinutes: 0,
      instructions: 'Delivered fully assembled in reinforced protective boxes.',
    },
    spatialSuitability: 'Sleek profile allows 6 chairs to fit seamlessly along 180cm tables like the Veda.',
    featured: false,
    leadTimeWeeks: 2,
    origin: 'Handmade in Jodhpur, India',
    images: [
      {
        id: 'dhyaan-hero',
        src: '/images/products/dhyaan_dining_chair_hero.png',
        alt: 'Dhyaan Spindle Dining Chair in solid teakwood with steam-bent backrest',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'dhyaan-pair',
        src: '/images/products/dhyaan_dining_chair_pair.png',
        alt: 'Pair of Dhyaan Dining Chairs tucked alongside a natural wood dining table',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'dhyaan-detail',
        src: '/images/products/dhyaan_dining_chair_detail.png',
        alt: 'Macro shot of spindle joinery and curved backrail on Dhyaan Dining Chair',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-08',
    slug: 'kosh-sideboard',
    name: 'Kosh Slatted Credenza',
    tagline: 'Low-profile architectural storage with rhythmic fluted tambour doors and solid brass pulls.',
    description:
      'The Kosh Credenza brings calm, orderly storage to dining and living spaces. Its slatted sliding tambour doors glide effortlessly along integrated tracks, concealing generous shelving for dinnerware, media components, or bar collections.',
    detailedStory:
      'Milled with micro-slats in natural teak veneer over an architectural solid frame, Kosh allows infrared remote signals to pass through while keeping clutter hidden. The top surface offers a broad staging area for ceramic vessels, lamps, and framed art.',
    category: 'storage',
    categoryLabel: 'Storage',
    roomCategories: ['dining', 'living'],
    roomLabels: ['Dining Room', 'Living Room'],
    priceINR: 34900,
    primaryMaterial: 'Teak Veneer',
    materialsList: [
      'Architectural Teak Veneer on FSC Birch Substrate with Solid Teak Edging',
      'Solid Teak Slat Tambour Doors with Precision Polymer Glide Tracks',
      'Custom Solid Brushed Brass Handle Knobs',
      'Blum Soft-Close Internal Drawer Runners',
    ],
    colors: [
      { name: 'Natural Warm Teak', code: 'natural-teak', hex: '#9E6D38', materialName: 'Teak / Brass' },
      { name: 'Smoked Walnut Finish', code: 'smoked-walnut', hex: '#4A3525', materialName: 'Walnut / Brass' },
    ],
    dimensions: {
      widthCm: 160,
      depthCm: 45,
      heightCm: 74,
      clearanceCm: 16,
      weightKg: 48,
      formatted: '160 × 45 × 74 cm',
    },
    constructionDetails: [
      'Internal cable management grommets for media consoles and sound systems.',
      'Adjustable internal shelves with 3 height settings on each side.',
      'Solid timber splayed plinth base with central structural support leg.',
    ],
    careInstructions: [
      'Dust slats using a feather duster or soft vacuum attachment.',
      'Wipe top surface with wood-safe cleaner.',
    ],
    assemblyInfo: {
      required: true,
      level: 'White-Glove Assembly Provided',
      estimatedMinutes: 20,
      instructions: 'Delivered pre-built. Logistics team attaches the plinth base and levels the internal shelves.',
    },
    spatialSuitability: 'Ideal as a dining buffet or an elegant media console for TVs up to 65 inches.',
    featured: true,
    leadTimeWeeks: 3,
    origin: 'Crafted in Ahmedabad, India',
    images: [
      {
        id: 'kosh-hero',
        src: '/images/products/kosh_sideboard_hero.png',
        alt: 'Kosh Slatted Credenza in natural teak with brass pulls and sliding tambour doors',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'kosh-open',
        src: '/images/products/kosh_sideboard_open.png',
        alt: 'Kosh Credenza with one tambour door open revealing spacious internal wood shelving',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'kosh-detail',
        src: '/images/products/kosh_sideboard_detail.png',
        alt: 'Detail of brushed brass handle and fluted teak slats on Kosh Credenza',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-09',
    slug: 'sopan-shelving-unit',
    name: 'Sopan Open Modular Shelving',
    tagline: 'Minimalist vertical architecture combining solid teak uprights and matte charcoal steel trays.',
    description:
      'Sopan (meaning steps) creates an open, luminous room divider or wall display. Its ladder-like solid teak uprights support precision-folded matte steel shelves, offering a restrained stage for books, tropical indoor foliage, and curated artifacts.',
    detailedStory:
      'Designed to maintain natural light flow across urban open-plan apartments, Sopan does not block window light. The folded steel shelf lips keep books upright without separate bookends, while the teak uprights anchor the unit with organic warmth.',
    category: 'storage',
    categoryLabel: 'Storage',
    roomCategories: ['study', 'living'],
    roomLabels: ['Study', 'Living Room'],
    priceINR: 24900,
    primaryMaterial: 'Powder-Coated Steel',
    materialsList: [
      'Solid Kiln-Dried Indian Teak Upright Columns',
      '1.8mm Laser-Cut and CNC-Folded Steel Shelves with Matte Charcoal Powder Coating',
      'Precision Brass Hardware Fasteners',
    ],
    colors: [
      { name: 'Natural Teak & Matte Charcoal', code: 'teak-charcoal', hex: '#9E6D38', materialName: 'Teak / Steel' },
      { name: 'Natural Teak & Sand White', code: 'teak-sand', hex: '#E2DBD0', materialName: 'Teak / Steel' },
    ],
    dimensions: {
      widthCm: 100,
      depthCm: 35,
      heightCm: 180,
      clearanceCm: 12,
      weightKg: 28,
      formatted: '100 × 35 × 180 cm',
    },
    constructionDetails: [
      '5 tier open architectural shelving with 34cm vertical clearance between tiers.',
      'Concealed anti-tip wall anchor hardware kit included for safety in high-rise buildings.',
      'Modular shelf trays lock securely into CNC-machined recesses in the teak uprights.',
    ],
    careInstructions: [
      'Dust shelves with a microfibre cloth.',
      'Clean steel trays with a damp cloth; wipe dry immediately.',
    ],
    assemblyInfo: {
      required: true,
      level: 'Simple (Leg Attachment)',
      estimatedMinutes: 20,
      instructions: 'Interlock the 5 steel shelf trays into the two teak uprights using provided hex keys and brass bolts.',
    },
    spatialSuitability: 'Works as a study bookcase or an airy room divider between living and dining zones.',
    featured: false,
    leadTimeWeeks: 2,
    origin: 'Crafted in Bengaluru, India',
    images: [
      {
        id: 'sopan-hero',
        src: '/images/products/sopan_shelving_unit_hero.png',
        alt: 'Sopan Open Modular Shelving unit with solid teak uprights and charcoal steel shelves',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'sopan-styled',
        src: '/images/products/sopan_shelving_unit_styled.png',
        alt: 'Sopan Shelving styled with art books, ceramic pots, and small indoor plants in a study',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'sopan-detail',
        src: '/images/products/sopan_shelving_unit_detail.png',
        alt: 'Close-up of teak column joint and folded matte steel shelf lip on Sopan Unit',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-10',
    slug: 'nidra-platform-bed',
    name: 'Nidra Low Platform Bed',
    tagline: 'Floating solid teak bed frame with integrated cantilevered nightstands and padded headboard.',
    description:
      'The Nidra Bed is a grounded sanctuary designed to evoke tranquility and restorative sleep. Its recessed plinth creates a serene floating aesthetic, while the upholstered linen headboard provides an angled backrest for late-night reading.',
    detailedStory:
      'Engineered with an internal acoustic suspension system, Nidra eliminates nocturnal squeaks. The solid teak perimeter is broad enough to perch on in the morning. Solid beech wood sprung slats provide adaptive spinal support for all standard king-size mattresses.',
    category: 'bedroom',
    categoryLabel: 'Bedroom',
    roomCategories: ['bedroom'],
    roomLabels: ['Bedroom'],
    priceINR: 44900,
    primaryMaterial: 'Solid Teak',
    materialsList: [
      'Solid Indian Teak Floating Outer Perimeter and Headboard Frame',
      'Upholstered Oatmeal Linen Headboard Inset with High-Resilience Foam',
      'Solid Birch Flexible Sprung Slat Base with Center Steel Support Spine',
    ],
    colors: [
      { name: 'Warm Teak & Oatmeal Linen', code: 'teak-oat', hex: '#9E6D38', materialName: 'Teak / Linen' },
      { name: 'Smoked Teak & Muted Sage Linen', code: 'smoked-sage', hex: '#588157', materialName: 'Teak / Sage Linen' },
    ],
    dimensions: {
      widthCm: 205,
      depthCm: 188,
      heightCm: 92,
      seatHeightCm: 28,
      clearanceCm: 18,
      weightKg: 74,
      formatted: '205 × 188 × 92 cm (King)',
    },
    constructionDetails: [
      'Recessed structural plinth provides 18cm floor clearance and floating silhouette.',
      'Heavy-duty steel corner brackets prevent squeaks and frame shift over time.',
      'Fits standard 78 × 72 inch (198 × 183 cm) King size Indian mattresses.',
    ],
    careInstructions: [
      'Vacuum the upholstered headboard monthly with a soft brush attachment.',
      'Wipe down teak perimeter with a dry cloth.',
    ],
    assemblyInfo: {
      required: true,
      level: 'White-Glove Assembly Provided',
      estimatedMinutes: 30,
      instructions:
        'Delivered flat-packed in 3 cartons. Our technicians assemble the floating plinth, outer perimeter rails, headboard, and drop-in sprung slat cassette.',
    },
    spatialSuitability: 'Low horizontal profile visually expands ceiling height in urban bedrooms.',
    featured: true,
    leadTimeWeeks: 4,
    origin: 'Crafted in Ahmedabad & Jodhpur, India',
    images: [
      {
        id: 'nidra-hero',
        src: '/images/products/nidra_platform_bed_hero.png',
        alt: 'Nidra Low Platform Bed in solid teakwood with oatmeal linen headboard in a calm bedroom',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'nidra-angle',
        src: '/images/products/nidra_platform_bed_angle.png',
        alt: 'Three-quarter angle showing floating plinth base of Nidra Platform Bed',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'nidra-detail',
        src: '/images/products/nidra_platform_bed_detail.png',
        alt: 'Macro shot of solid teak corner joinery and oatmeal headboard fabric on Nidra Bed',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
  {
    id: 'prod-11',
    slug: 'aksh-floor-lamp',
    name: 'Aksh Spun Brass Floor Lamp',
    tagline: 'Warm ambient beacon with turned teak column and spun brass reflector disc.',
    description:
      'Aksh casts a warm, glare-free indirect glow that transforms evening living spaces. Its turned teak column rests on a heavy cast-iron base with a spun brass foot, while the linen drum shade diffuses warm ambient light at eye level.',
    detailedStory:
      'Inspired by traditional Indian oil lamp proportions, Aksh replaces harsh ceiling downlights with gentle atmospheric illumination. Features a braided fabric power cord with a brass step-on floor switch.',
    category: 'objects',
    categoryLabel: 'Selected Objects',
    roomCategories: ['living', 'study', 'bedroom'],
    roomLabels: ['Living Room', 'Study', 'Bedroom'],
    priceINR: 8900,
    primaryMaterial: 'Spun Brass',
    materialsList: [
      'Hand-Spun Solid Brass Base Ferrule and Top Disc',
      'Solid Lathe-Turned Indian Teakwood Column',
      'Woven Natural Linen Diffuser Shade',
      'Braided Jute Cable with Solid Brass In-Line Foot Switch',
    ],
    colors: [
      { name: 'Warm Brass & Natural Teak', code: 'brass-teak', hex: '#C5A059', materialName: 'Brass / Teak' },
    ],
    dimensions: {
      widthCm: 38,
      depthCm: 38,
      heightCm: 145,
      weightKg: 8.5,
      formatted: '38 × 38 × 145 cm',
    },
    constructionDetails: [
      'Weighted 6kg cast-iron internal sub-base prevents tipping.',
      'Standard E27 brass lamp holder compatible with dimmable LED warm bulbs (2700K recommended).',
      '2.5-meter braided textile cord.',
    ],
    careInstructions: [
      'Wipe brass with a dry microfiber cloth; do not use chemical brass cleaners to allow natural patina development.',
    ],
    assemblyInfo: {
      required: true,
      level: 'Simple (Leg Attachment)',
      estimatedMinutes: 5,
      instructions: 'Thread the teak stem into the weighted base. Fit shade and collar ring. Bulb not included.',
    },
    spatialSuitability: 'Elevates dim room corners beside the Kaya chair or sofa.',
    featured: false,
    leadTimeWeeks: 1,
    origin: 'Crafted in Moradabad & Ahmedabad, India',
    images: [
      {
        id: 'aksh-hero',
        src: '/images/products/aksh_floor_lamp_hero.png',
        alt: 'Aksh Floor Lamp with turned teak stem and spun brass base casting warm light',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'hero',
      },
      {
        id: 'aksh-ambient',
        src: '/images/products/aksh_floor_lamp_ambient.png',
        alt: 'Aksh Floor Lamp glowing warmly in an evening living room corner',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'gallery',
      },
      {
        id: 'aksh-detail',
        src: '/images/products/aksh_floor_lamp_detail.png',
        alt: 'Close-up of spun brass ferrule and turned teak grain on Aksh Lamp',
        width: 1600,
        height: 1200,
        aspectRatio: '4:3',
        role: 'detail',
      },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(currentSlug: string, limit = 3): Product[] {
  const current = getProductBySlug(currentSlug);
  if (!current) return PRODUCTS.slice(0, limit);
  return PRODUCTS.filter(
    (p) =>
      p.slug !== currentSlug &&
      (p.category === current.category ||
        p.roomCategories.some((rc) => current.roomCategories.includes(rc)))
  ).slice(0, limit);
}
